# Site settings - 直接配置值
title: "个人官网"
email: "zhao999ss@163.com"
brand: "个人品牌"
headline: "全栈开发者 & 技术创新者"
description: "个人官网，展示技术能力、项目作品和个人见解。致力于创造优雅的用户体验和高质量的技术解决方案。"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fxxk181126.github.io" # the base hostname & protocol for your site
copyright: "2025 个人官网. All Rights Reserved."

# Personal Information - 直接配置
author:
  name: "Zane"
  display_name: "Zane"
  title: "全栈开发者"
  bio: "热爱技术创新，专注于前端开发和用户体验设计"
  location: "中国"
  avatar: "/assets/images/avatar.svg"
  experience: "3+"

# Social Media - 直接配置
social:
  github: "https://github.com/Fxxk181126"
  linkedin: "#"
  twitter: "#"
  email: "zhao999ss@163.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 6
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Sass
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass

# Assets
assets:
  sources:
    - assets/images
    - assets/js
    - assets/css

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - _web-src
  - web-dist
  - "*.backup.tar.gz"
  - .git
  - .gitignore
  - .trae

# SEO settings
lang: zh-CN
timezone: Asia/Shanghai

# SEO settings - 直接配置
seo:
  type: "Person"
  name: "Zane"
  links:
    - "https://github.com/Fxxk181126"
    - "https://fxxk181126.github.io"

# Open Graph / Twitter Card defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/images/og-image.png"
      author: "Zane"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Zane"
      image: "/assets/images/blog-default.png"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Zane"

# Google Analytics (replace with your tracking ID)
google_analytics: "G-XXXXXXXXXX"

# Webmaster verification
google_site_verification: ""
bing_site_verification: ""

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: true

# Theme colors (Vue.js inspired)
theme_colors:
  primary_color: "#42b883"
  secondary_color: "#35495e"
  accent_color: "#007bff"
  text_color: "#2c3e50"
  background_color: "#ffffff"
  light_gray: "#f8f9fa"
  dark_gray: "#6c757d"
  success_color: "#28a745"
  warning_color: "#ffc107"
  danger_color: "#dc3545"

# Navigation
navigation:
  - title: "首页"
    url: "/"
  - title: "关于我"
    url: "/about/"
  - title: "项目作品"
    url: "/projects/"
  - title: "博客"
    url: "/blog/"
  - title: "联系我"
    url: "/contact/"

