# Site settings - 引用统一的个人信息配置
title: "{{ site.data.personal.site.title }}"
email: "{{ site.data.personal.contact.email }}"
brand: "{{ site.data.personal.site.brand }}"
headline: "{{ site.data.personal.site.headline }}"
description: "{{ site.data.personal.site.description }}"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fxxk181126.github.io" # the base hostname & protocol for your site
copyright: "{{ site.data.personal.site.copyright }}"

# Personal Information - 引用统一配置
author:
  name: "{{ site.data.personal.basic.name }}"
  display_name: "{{ site.data.personal.basic.display_name }}"
  title: "{{ site.data.personal.basic.title }}"
  bio: "{{ site.data.personal.basic.bio }}"
  location: "{{ site.data.personal.basic.location }}"
  avatar: "{{ site.data.personal.basic.avatar }}"
  experience: "{{ site.data.personal.basic.experience }}"

# Social Media - 引用统一配置
social:
  github: "{{ site.data.personal.social.github.url }}"
  linkedin: "{{ site.data.personal.social.linkedin.url }}"
  twitter: "{{ site.data.personal.social.twitter.url }}"
  email: "{{ site.data.personal.contact.email }}"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 6
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Sass
sass:
  sass_dir: _web-src/scss
  style: compressed
  load_paths:
    - _web-src/scss

# Assets
assets:
  sources:
    - assets/images
    - assets/js
    - assets/css

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - LICENSE.md
  - _web-src
  - web-dist

# SEO settings
lang: zh-CN
timezone: Asia/Shanghai

# SEO settings - 引用统一配置
seo:
  type: "{{ site.data.personal.seo.type }}"
  name: "{{ site.data.personal.basic.name }}"
  links:
    - "{{ site.data.personal.social.github.url }}"
    - "https://fxxk181126.github.io"

# Open Graph / Twitter Card defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/images/og-image.png"
      author: "Zane"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Zane"
      image: "/assets/images/blog-default.png"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Zane"

# Google Analytics (replace with your tracking ID)
google_analytics: "G-XXXXXXXXXX"

# Webmaster verification
google_site_verification: ""
bing_site_verification: ""

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: true

# Theme colors (Vue.js inspired)
theme:
  primary_color: "#42b883"
  secondary_color: "#35495e"
  accent_color: "#007bff"
  text_color: "#2c3e50"
  background_color: "#ffffff"
  light_gray: "#f8f9fa"
  dark_gray: "#6c757d"
  success_color: "#28a745"
  warning_color: "#ffc107"
  danger_color: "#dc3545"

# Navigation
navigation:
  - title: "首页"
    url: "/"
  - title: "关于我"
    url: "/about/"
  - title: "项目作品"
    url: "/projects/"
  - title: "博客"
    url: "/blog/"
  - title: "联系我"
    url: "/contact/"

